# file: .travis.yml
language: objective-c
osx_image: xcode7.3 
script:
  - pod install
  - xcodebuild -workspace TravisSample.xcworkspace -scheme TravisSample -destination 'platform=iOS Simulator,name=iPhone 6,OS=9.3' clean test
