language: objective-c
osx_image: xcode7.3
before_script:
- "./scripts/travis/add-key.sh"
after_script:
- "./scripts/travis/remove-key.sh"
after_success:
- "./scripts/travis/build.sh"
env:
  global:
  - PROFILE_UUID="dd107f78-5e96-4f08-8faa-adaaaa8a5185"
  - APP_NAME="TravisSample"
  - DEVELOPER_NAME='DEVELOPER_NAME="iPhone Distribution: Interactive Labs, Inc"'
