language: objective-c
osx_image: xcode7.3
before_script:
- ./scripts/travis/add-key.sh   
after_script:
- ./scripts/travis/remove-key.sh
after_success:
- ./scripts/travis/build.sh
env:
  global:
  - PROFILE_NAME="iLabs_Wild_Card_alt_certificate_Distribution"
  - APP_NAME="TravisSample"
  - 'DEVELOPER_NAME="iPhone Distribution: Interactive Labs, Inc"'
  secure: jIqnMGXjwEM+TS4aEYLKwi/wCebLB2ESyIdLR4n8dYydIDg+u55w3JOcyVUvHFvqcoHBE8u8p8bPpC/xmx7JVErCDNldXHtX1/G5wGqSWnvefJmI5wJWparihcIBQIK27baHRcztsBbwL06r9YFerCwC/EzS3ijBwlmmz2/idOZfLPN994AHvzj+2FN3jrHs1uy795QRvHovFQE+Y36V+GLKZx+3QuSCJMK6DPKxQMQRsgQDS13+V9TJRH2pNvIPVvKuUKWG0zRzo21b8kKPr4s41ey3m8LyJnDIzTMoPmq7WctyAqQSAL7Egm1mAyit6/1Wsxgq8XEVIVuImWn1VC78gUfpbRoyg6+baoLrZAHO7f0Xa0H7N/3NTH0RHA9kdXQJgF3yueqFgufguJp3msC84ReYwfFcvxGNyoVc6zYonBV8m7MSvdzmF/jTfsoSeH41UB8ly7BxZs3Vo72ocIVBxqtkxA6uVCOEp95YXd9BnO9staT8bYzXozuzwhiofpYOVszozh0dRI257OCVXAY3kYd8xzytDPbvlYLYiRweGPmnYOgFwOukJokfP/6UuldpxTLolS+P5wxKG4tQiZty/JGSlgVWWwU7OqnqNai7e628MgLocjUAXa4s3kcxT8WZOUbt5gdPBAme8BwarprSIB9sQB335y9qSHfek4U=
